name: Continuous Integration
on: push
jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 12.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 12.x
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint